image: openjdk:8-slim-bullseye
stages:
  - build

build:
  image: openjdk:8-slim-bullseye
  stage: build
  before_script:
    #- yum install hamcrest junit
    - apt-get -qq update && apt-get install -y libhamcrest-java junit4 ant maven gradle
  script:
     - cd ant && ant -noinput -buildfile build.xml
