image: openjdk:8-slim-bullseye
stages:
  - build

build:
  image: openjdk:8-slim-bullseye
  stage: build
  before_script:
    - sudo yum install hamcrest junit
    #   - apt-get -qq update && apt-get install libhamcrest-java junit4
  script:
     - cd ant && ant -noinput -buildfile build.xml
