# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI with ant

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Install deps
      run: sudo apt-get install -y libhamcrest-java junit4
    - name: Build with Ant
      run: cd ant && ant -noinput -buildfile build.xml
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ant.jar
        path: ant/dist/lib/*.jar
