name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Install deps
      run: sudo apt-get install -y libhamcrest-java junit4
    - name: Build with Ant
      run: cd ant && ant -noinput -buildfile build.xml
    - name: Build with Maven
      run: cd maven/my-app && mvn -B package --file pom.xml
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "ant/dist/lib/ant.jar,maven/my-app/target/my-app*.jar"
        body: "a new test release"
        token: ${{ secrets.GITHUB_TOKEN }}